# .github/workflows/build.yml

name: Build Application

on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: Build OpenCore Legacy Patcher
    runs-on: macos-12 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build the Application
        run: python3 Build-Project.command

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher-Build
          path: dist/
